// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package queries

import (
	"database/sql"
)

type Member struct {
	Username     string
	Name         string
	Picture      sql.NullString
	PictureThumb sql.NullString
	JoinDate     sql.NullString
	ReferTo      sql.NullString
	ContactInfo  sql.NullString
	Interests    sql.NullString
	Badges       []string
	Board        bool
	Sudoer       bool
}
