name: Build debug Docker image

on:
  - push
  - pull_request

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.repository == 'hacklabto/members-platform'
    steps:
      - uses: actions/checkout@v3
      - uses: docker/build-push-action@v2
        with:
          # https://github.com/docker/build-push-action/issues/378
          context: .
          file: Dockerfile
          push: false
          tags: |
            ghcr.io/hacklabto/members-platform:${{ github.sha }}
